using System;
using System.Collections;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Windows.Forms;
using System.Xml;
using System.Threading;

namespace Dynamic.Script_8D671B7447E7316
{
	// Script generated by Pega Robotics Studio 8.0.1096.0
	// Please use caution when modifying class name, namespace or attributes
	[OpenSpan.TypeManagement.DynamicTypeAttribute()]
	[OpenSpan.Design.ComponentIdentityAttribute("Script-8D671B7447E7316")]
	public sealed class Script
	{
		public string TimerStart()
		{
			int saat = 0, dakika = 0, saniye = 0;
			while (true)
			{
				if (saniye == 59)
				{
					saniye = 0;
					dakika = dakika + 1;
					if (dakika == 60)
					{
						saniye = 0;
						dakika = 0;
						saat = saat + 1;
					}
				}
				saniye = saniye + 1;
				Thread.Sleep(1000);
				return Convert.ToString(saat) + " : " + Convert.ToString(dakika) + " : " + Convert.ToString(saniye);
			}

		}	

	}
}
